### ISSUE TITLE
Error in mfrpred.ipynb

### ISSUE THREAD

**Issue by hruedisser** [helioforecast/Papers#6]
Section 4 analogue ensembles gives:

ValueError                                Traceback (most recent call last)
<ipython-input-15-b03a07facb7f> in <module>
     31 for p in np.arange(0, np.size(iwinind)):
     32     btot_tw_temp = win['bt'][np.where(np.logical_and(win['time'] >= (mo_start_time_num[iwinind[p]] - tw_hrs_start / 24.0), win['time'] < (mo_start_time_num[iwinind[p]] + tw_hrs_end / 24.0)))]
---> 33     btot_tw[:, p] = btot_tw_temp
     34 
     35     bz_tw_temp = win['bz'][np.where(np.logical_and(win['time'] >= (mo_start_time_num[iwinind[p]] - tw_hrs_start / 24.0), win['time'] < (mo_start_time_num[iwinind[p]] + tw_hrs_end / 24.0)))]

ValueError: could not broadcast input array from shape (728) into shape (1455)

**Comment by cmoestl** [comment]
We now use only these 2 notebooks for the paper results: mfrpred_mreiss_bz.ipynb and mfrpred_mreiss_bz.ipynb

**Comment by hruedisser** [comment]
Thanks for the clarification!

Another thing I came across in mfrpred_mreiss_bz: "ValueError: too many values to unpack (expected 2)"

This can be solved by exchanging "# Load STEREO-B data [stb, attb] = pickle.load(open("data/stereob_2007_2014_sceq_ndarray.p", "rb")) " with "[stb, attb, header] "

**Comment by cmoestl** [comment]
Yes indeed, thanks! I had a different stereob_ file in use - one has to load it with 3 values. I've also updated the installation instructions in the README.md to use version 8 from here https://doi.org/10.6084/m9.figshare.12058065.v8
